baseURL = "https://jvdwalle.github.io/indipop-lab/"
title = "IndiPop Lab"
theme = "ananke-main"
canonifyURLs = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

############################
# Languages
############################

[languages]

  [languages.en]
    languageName = "English"
    languageCode = "en-CA"
    weight = 1

    [[languages.en.menu.main]]
      name = "People"
      pageRef = "/people"
      weight = 10

    [[languages.en.menu.main]]
      name = "Research"
      pageRef = "/research"
      weight = 20

    [[languages.en.menu.main]]
      name = "Publications"
      pageRef = "/publications"
      weight = 30

    [[languages.en.menu.main]]
      name = "Opportunities"
      pageRef = "/opportunities"
      weight = 50

    [[languages.en.menu.main]]
      name = "Contact"
      pageRef = "/contact"
      weight = 70


  [languages.fr]
    languageName = "Français"
    languageCode = "fr-CA"
    weight = 2

    [[languages.fr.menu.main]]
      name = "Équipe"
      pageRef = "/people"
      weight = 10

    [[languages.fr.menu.main]]
      name = "Recherche"
      pageRef = "/research"
      weight = 20

    [[languages.fr.menu.main]]
      name = "Publications"
      pageRef = "/publications"
      weight = 30

    [[languages.fr.menu.main]]
      name = "Opportunités"
      pageRef = "/opportunities"
      weight = 50

    [[languages.fr.menu.main]]
      name = "Contact"
      pageRef = "/contact"
      weight = 70